// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2421.Minotaur;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController leftMotor1;
    public static SpeedController leftMotor2;
    public static SpeedController rightMotor1;
    public static SpeedController rightMotor2;
    public static DoubleSolenoid doubleSolenoid1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        leftMotor1 = new Spark(0);
        LiveWindow.addActuator("Motors", "leftMotor1", (Spark) leftMotor1);
        
        leftMotor2 = new Spark(1);
        LiveWindow.addActuator("Motors", "leftMotor2", (Spark) leftMotor2);
        
        rightMotor1 = new Spark(2);
        LiveWindow.addActuator("Motors", "rightMotor1", (Spark) rightMotor1);
        
        rightMotor2 = new Spark(3);
        LiveWindow.addActuator("Motors", "rightMotor2", (Spark) rightMotor2);
        
        doubleSolenoid1 = new DoubleSolenoid(0, 1);
        LiveWindow.addActuator("Pneumatics", "Double Solenoid 1", doubleSolenoid1);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
